// Generated by https://quicktype.io

export interface Profile {
    id:          string;
    email:       string;
    user_role:   string;
    user_status: string;
    created_at:  Date;
    updated_at:  Date;
    deleted_at:  null;
    doctor:      Doctor[];
}

export interface Doctor {
    id:   string;
    name: string;
}
