import { nautilusApi } from "../../api/nautilus.api";


// Generated by https://quicktype.io

export interface AppointmentInterface {
    id: string;
    appointment_date: string;
    appointment_status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
    address_snapshot: string;
    email_snapshot: string;
    phone_number_snapshot: string;
    comment: string;
    doctor_id: string;
    patient_id: string;
    created_at: Date;
    updated_at: null;
    deleted_at: null;
    patient: Patient;
}

export interface Patient {
    name: string;
    rut: string;
}

export const getAppointments = async (doctor_id: string): Promise<AppointmentInterface[]> => {
    try {
        const response = await nautilusApi.get(`appointments?doctorID=${doctor_id}`)
        return response.data;
    } catch (err) {
        console.log(err)
        throw err
    }
}